baseurl = "http://www.vle-project.org/"
languageCode = "en-us"
title = "Virtual Laboratory Environment"
MetaDataFormat = "toml"
theme = "blackburn"
canonifyurls = true
paginate = 10
author = "INRA"
copyright = "&copy; 2016 INRA"

[indexes]
 tag="tags"
 topic="topics"

[params]
 subtitle = "A Modeling & Simulation Environment"
 brand = "VLE"
 highlightjs = "androidstudio"
 dateFormat = "02 Jan 2006, 15:04"

[menu]
 [[menu.main]]
  name = "Home"
  pre = "<i class='fa fa-home fa-fw'></i>"
  weight = 0
  identifier = "home"
  url = "/"
 [[menu.main]]
  name = "About"
  pre = "<i class='fa fa-user fa-fw'></i>"
  weight = 1
  identifier = "about"
  url = "/about/"
 [[menu.main]]
  name = "VLE 1.1 (stable)"
  pre = "<i class='fa fa-download fa-fw'></i>"
  weight = 2
  identifier = "VLE 1.1"
  url = "/vle-11/"
 [[menu.main]]
  name = "VLE 2.0 (dev.)"
  pre = "<i class='fa fa-download fa-fw'></i>"
  weight = 3
  identifier = "VLE 2.0"
  url = "/vle-20/"
 [[menu.main]]
  name = "Documentation"
  pre = "<i class='fa fa-book fa-fw'></i>"
  weight = 4
  identifier = "documentation"
  url = "/documentation/"
 [[menu.main]]
  name = "Tutorials"
  pre = "<i class='fa fa-check-square-o fa-fw'></i>"
  weight = 5
  identifier = "Tutorials"
  url = "/tutorials/"
 [[menu.main]]
  name = "Discussion"
  pre = "<i class='fa fa-phone fa-fw'></i>"
  weight = 6
  identifier = "Discussion"
  url = "/discussion/"
 [[menu.main]]
  name = "Posts"
  pre = "<i class='fa fa-list fa-fw'></i>"
  weight = 7
  identifier = "post"
  url = "/post/"
 [[menu.main]]
  name = "Topics"
  pre = "<i class='fa fa-folder fa-fw'></i>"
  weight = 8
  identifier = "topic"
  url = "/topics/"
 [[menu.main]]
  name = "Tags"
  pre = "<i class='fa fa-tags fa-fw'></i>"
  weight = 9
  identifier = "tag"
  url = "/tags/"
    
[social]
 github = "vle-forge"
 facebook = "groups/vle.project"
